apiVersion: v1
kind: Secret
metadata:
  name: foo
  namespace: sciety
data:
  postgresql-database: cG9zdGdyZXM=
  postgresql-username: cG9zdGdyZXM=
  postgresql-password: VkdOTGRFZGtlSGg1TVU5MU1HUllOa2hTVERsM01YSms=
  postgresql-host: c2NpZXR5LWRlbW8uY3h5b3BuNDR1cWJsLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  postgresql-port: NTQzMg==
