apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: sciety-demo
  namespace: sciety
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t4g.micro
  dbInstanceIdentifier: sciety-demo
  engine: postgres
  engineVersion: "12"
  masterUsername: "postgres"
  masterUserPassword:
    name: demo-database
    key: password
  vpcSecurityGroupIDs:
    - sg-0a04b1c8433227e63
  dbSubnetGroupName: elife-flux-prod-ack-rds-controller-all-dbs

