apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sciety--demo
  namespace: sciety
spec:
  releaseName: sciety--demo
  interval: 5m
  chart:
    spec:
      chart: helm/sciety
      sourceRef:
        kind: GitRepository
        name: sciety
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: crossref-api
      valuesKey: bearerToken
      targetPath: crossrefApiBearerToken
  values:
    postgresqlSecretName: foo
    hostname: sciety-demo.elifesciences.org
    ingestionAuthBearerToken: not-really-secret-bearer-token
    images:
      frontend:
        tag: 1e833367f35db08e8c439bf4b55546f7de6491a1
    experimentEnabled: ""
    appSecret: unsafe-secret
    appCache: redis
    auth0ClientId: bogus-auth0-client-id
    auth0ClientSecret: bogus-auth0-client-secret
    auth0Domain: sciety-staging.eu.auth0.com
    auth0CallbackUrl: "https://staging.sciety.org/auth0/callback"
    googleTagManagerId: ""
    prelightsFeedKey: bogus-prelights-feed-key
    healthchecksPingKey: bogus-healthchecks-ping-key
    enableEventsExportToS3: false
    certManagerClusterIssuer: letsencrypt-prod
