---
apiVersion: v1
kind: Service
metadata:
  name: coar-notify-inbox--demo
  labels:
    app.kubernetes.io/name: sciety
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/component: coar-notify-inbox
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 80
      protocol: TCP
  selector:
    application: coar-notify-inbox--demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coar-notify-inbox--demo
  labels:
    app.kubernetes.io/name: sciety
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/component: coar-notify-inbox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: coar-notify-inbox-sciety-demo.elifesciences.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coar-notify-inbox--demo
                port:
                  number: 80
  tls:
    - hosts:
        - coar-notify-inbox-sciety-demo.elifesciences.org
      secretName: sciety--demo--coar-notify-inbox--letsencrypt-cert
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coar-notify-inbox-database
  labels:
    app.kubernetes.io/name: sciety
    app.kubernetes.io/instance: sciety--demo
    app.kubernetes.io/component: coar-notify-inbox
spec:
  interval: 1m
  releaseName: coar-notify-inbox-database
  chart:
    spec:
      chart: psmdb-db
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: db-operator-system
      interval: 1m

  values:
    image:
      repository: percona/percona-server-mongodb
      tag: 7.0.14-8-multi
    sharding:
      enabled: false
    backup:
      enabled: false
    replsets:
      rs0:
        volumeSpec:
          pvc:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: csi-ebs-gp3
            resources:
              requests:
                storage: 20Gi
