---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coar-notify-inbox--demo
spec:
  #  Missing mandatory property `spec.selector` supplied via Kustomize
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: dragasteff/coar-notify-inbox:0.0.3-amd64
        env: 
        - name: _MONGO_DB_HOSTNAME
          value: coar-notify-inbox-dat-rs0
        - name: _MONGO_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: coar-notify-inbox-dat-secrets
              key: MONGODB_DATABASE_ADMIN_USER
        - name: _MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coar-notify-inbox-dat-secrets
              key: MONGODB_DATABASE_ADMIN_PASSWORD
        - name: MONGO_DB_URI
          value: "mongodb://$(_MONGO_DB_USERNAME):$(_MONGO_DB_PASSWORD)@$(_MONGO_DB_HOSTNAME):27017"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: coar-notify-inbox--demo
spec:
  type: ClusterIP
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coar-notify-inbox--demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: coar-notify-inbox-sciety-demo.elifesciences.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coar-notify-inbox--demo
                port:
                  number: 80
  tls:
    - hosts:
        - coar-notify-inbox-sciety-demo.elifesciences.org
      secretName: sciety--demo--coar-notify-inbox--letsencrypt-cert
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coar-notify-inbox-database
spec:
  interval: 1m
  releaseName: coar-notify-inbox-database
  chart:
    spec:
      chart: psmdb-db
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: db-operator-system
      interval: 1m

  values:
    image:
      repository: percona/percona-server-mongodb
      tag: 7.0.14-8-multi
    sharding:
      enabled: false
    backup:
      enabled: false
    replsets:
      rs0:
        volumeSpec:
          pvc:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: csi-ebs-gp3
            resources:
              requests:
                storage: 20Gi
